### ISSUE TITLE
sitemap via SRR not working on zeit now

### ISSUE THREAD

**Issue by miteyema** [nuxt-community/sitemap-module#106]
### Version

[2.0.1](https://github.com/sitemap-module/releases/tag/2.0.1)

### Reproduction link

[https://github.com/miteyema/nuxt-sitemap-now](https://github.com/miteyema/nuxt-sitemap-now)

### Steps to reproduce

- I have an api serverless function to return the dynamic routes so I can build a complete sitemap
- The dynamic routes are added to nuxt generate, so they are available for the sitemap module
- SRR app works in dev mode, but once deployed with zeit now in production (using nuxt/now-builder), it's not working
- If I use nuxt generate (to make a static app), sitemap does work

This is the config object for sitemap in nuxt.config.js:
```
 sitemap: {
    hostname: baseURL,
    defaults: {
      lastmod: new Date(),
      changefreq: 'weekly',
      priority: 0.8
    }
}
```

The generate part in nuxt.config.js:
```
generate: {
    async routes() {
      const response = await axios.get('routes', {
        // FYI: generate will always be in production mode
        baseURL: apiBaseURL
      })
      const dynamicRoutes = response.data
      return dynamicRoutes
    }
}
```

### What is expected ?

sitemap.xml is shown

### What is actually happening?

"Nuxt.js Internal Server Error" is show with status code 500.
The following log is shown on the server:

```
ERROR  Cannot read property 'filter' of null
  at node_modules/@nuxtjs/sitemap/lib/routes.js:14:21
  at Array.forEach (<anonymous>)
  at excludeRoutes (node_modules/@nuxtjs/sitemap/lib/routes.js:11:12)
  at Object.cache.staticRoutes (node_modules/@nuxtjs/sitemap/lib/middleware.js:48:30)
  at AsyncCache.load [as _load] (node_modules/@nuxtjs/sitemap/lib/cache.js:19:68)
  at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c82">#c82</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
@miteyema  thanks for your very complete report 👍 

I will investigate the root cause.

(issue linked to https://github.com/nuxt-community/sitemap-module/pull/95)

**Comment by NicoPennec** [comment]
@miteyema which version on this following doc, do you use to deploy?
https://nuxtjs.org/faq/now-deployment/
v2 or v1?

**Comment by miteyema** [comment]
@NicoPennec I have made a repo (configured with now) with only your sitemap module and I still have the same error:

Repo: https://github.com/miteyema/nuxt-sitemap-now
URL: https://nuxt-sitemap.now.sh/sitemap.xml

**Comment by JackMarksThomas** [comment]
I'm having a very similar issue where it's working locally however when it's in a live environment I am also getting Zeit Now internal server error. Though our sitemap module config is slightly different:

`  /**
  ** Sitemap module
  */
  sitemap: {
    // routes: async () => {
    //   const routes = await getRoutes()
    //   return routes
    // },
    // Still does not work if I hardcode the routes
    routes: [
      '/',
      'journal',
      '/journal/overview',
      '/journal/cbd-101',
      '/journal/medical',
      '/journal/wellness',
      '/journal/article/what-is-the-human-endocannabinoid-system',
      '/journal/article/what-is-cbd-oil',
      '/journal/article/what-is-cbd',
      '/journal/article/health-benefits',
      '/journal/article/meet-the-team',
      '/journal/article/it-s-legal-in-the-uk',
      '/faqs',
      '/lab-results',
      '/locations',
      '/privacy-cookies',
      '/delivery-and-returns',
      '/terms-and-conditions',
      '/contact',
      '/test-general-page',
    ],
    hostname: 'https://cannaray.co.uk',
    path: '/sitemap.xml',
    gzip: true,
    generate: false,
  },`

I believe this has been an issue for a few weeks since I first looked at the Sitemap, but have been working on other stuff since. May have to create my own sitemap.xml with a serverless function as we're going to be launching on Thursday

**Comment by NicolasPennec** [comment]
@miteyema I found the issue with Now and the sitemap-module.

This is due to the [`@nuxtjs/now-builder`](https://github.com/nuxt/now-builder) that doesn't copy the `sitemap-routes.json` file generated on `nuxt build` by the sitemap-module.

To fix your deploy, update your `now.json` configuration with the "serverFiles"  option setted as follows:

```json
{
  "version": 2,
  "builds": [
    {
      "src": "nuxt.config.js",
      "use": "@nuxtjs/now-builder",
      "config": {
        "serverFiles": [
          ".nuxt/dist/sitemap-routes.json"
        ]
      }
    }
  ]
}
```

**Comment by NicoPennec** [comment]
@miteyema I found the issue with Now and the sitemap-module.

This is due to the [`@nuxtjs/now-builder`](https://github.com/nuxt/now-builder) that doesn't copy the `sitemap-routes.json` file generated on `nuxt build` by the sitemap-module.

To fix your deploy, update your `now.json` configuration with the "serverFiles"  option setted as follows:

```json
{
  "version": 2,
  "builds": [
    {
      "src": "nuxt.config.js",
      "use": "@nuxtjs/now-builder",
      "config": {
        "serverFiles": [
          ".nuxt/dist/sitemap-routes.json"
        ]
      }
    }
  ]
}
```

**Comment by miteyema** [comment]
@NicoPennec Thank you so much for having a look at it and then solving it. Great work!

**Comment by heyjordn** [comment]
I've been searching for this solution for hours, thanks @NicoPennec

**Comment by NicoPennec** [comment]
It seems a common use case, so I will add a FAQ section to the README file.

**Comment by Youhan** [comment]
Looks like the FAQ is somehow removed. I couldn't find this in the docs

**Comment by teleyinex** [comment]
This is not mentioned on the docs, so it would be nice. The fix proposed by @NicoPennec works!
