### ISSUE TITLE
Sitemap looks weird

### ISSUE THREAD

**Issue by simplenotezy** [nuxt-community/sitemap-module#135]
Is the sitemap supposed to look like this?

![image](https://user-images.githubusercontent.com/3786627/84602583-cf9a4280-ae88-11ea-9d50-59405bbd635c.png)

It looks kinda malformed.

**Comment by brumartins** [comment]
I had the same concern but I guess it's just a display issue. I checked mine with an online tool like 
[www.xml-sitemaps.com](https://www.xml-sitemaps.com/validate-xml-sitemap.html) and the sitemap was valid.

**Comment by NicoPennec** [comment]
It's only a rendering issue on your browser, due to the xml namespace of the elements `<xhtml:link>` when you used the "i18n" option. Your browser will convert the XML rendering to a XHTML page rendering because it see a know `xhtml:*` namespace.

See https://support.google.com/chrome/thread/10921150?hl=en and https://bugs.chromium.org/p/chromium/issues/detail?id=580033

Check the source code of the sitemap.xml, you will see that your XML file is valid.
Remember that the sitemap is an XML file for crawler, not for human ;)

**Comment by emilsgulbis** [comment]
I found this issue when switching to i18n mode. Validator says that .xml is ok, but browser doesn't render it
