### ISSUE TITLE
Internationalized routes are not being generated

### ISSUE THREAD

**Issue by leandromatos** [nuxt-community/sitemap-module#14]
Does this module not generate the sitemap for internationalized routes?

I used the following example to start a project, but the site map does not generate the routes for the pages that are within `pages/_lang/`.

https://nuxtjs.org/examples/i18n/

How can I do to generate the routes of these pages dynamically?

**Comment by NicoPennec** [comment]
No, it can't provide dynamic routes, because the sitemap should be generated one time for all routes (in real, keep in cache),  it's a little bit similar to "nuxt generate" mode.

When you build the example/i18n project you can see the routes create by nuxt in `./nuxt/router.js`

```js
    routes: [
		{
			path: "/", // static route
			component: _04553a5d,
			name: "index"
		},
		{
			path: "/about",  // static route
			component: _36c540d0,
			name: "about"
		},
		{
			path: "/:lang",  // dynamic route
			component: _47bceaac,
			name: "lang"
		},
		{
			path: "/:lang/about", // dynamic route
			component: _872ca036,
			name: "lang-about"
		}
    ]
```

So you have to declare your dynamic routes in the `nuxt.config.js` file (like in mode "generate"):
```js
module.exports = {
  loading: {
    color: "cyan"
  },
  build: {
    vendor: ["vue-i18n"]
  },
  router: {
    middleware: "i18n"
  },
  plugins: ["~/plugins/i18n.js"],
  generate: {
    routes: ["/", "/about", "/fr", "/fr/about"]
  },
  // sitemap config
  modules: ["@nuxtjs/sitemap"],
  sitemap: {
    routes: ["/", "/about", "/fr", "/fr/about"]
  }
};
```

Note that  `routes: ["/", "/about", "/fr", "/fr/about"]` can be replace by a function  to more flexibility.

Rebuild and your sitemap is good:
```xml

<urlset...>
   <url> <loc>http://localhost:3000/</loc> </url>
   <url> <loc>http://localhost:3000/about</loc> </url>
   <url> <loc>http://localhost:3000/fr</loc> </url>
   <url> <loc>http://localhost:3000/fr/about</loc> </url>
 </urlset>
```

**Comment by NicoPennec** [comment]
On this project, I create dynamic routes with the sitemap module : https://github.com/NicoPennec/nuxt-weather/blob/master/nuxt.config.js#L35

**Comment by leandromatos** [comment]
Thanks @NicoPennec ;)

**Comment by lxsedov** [comment]
it does not generate hreflang or alternate for dynamic routes

**Comment by NicoPennec** [comment]
Since the [v2.3.0](https://github.com/nuxt-community/sitemap-module/blob/dev/CHANGELOG.md#230-2020-05-11) the sitemap-module supports i18n routes from the nuxt-i18n module, but as before only for the static routes (see [features list](https://github.com/nuxt-community/sitemap-module#features))

But for now you can generate manually your dynamics routes with hreflang & alternate with the `links` attribute as follows:

```js
// nuxt.config.js

  i18n: {
    locales: ['en', 'de', 'fr'],
    defaultLocale: 'en',
  },
  sitemap: [
    {
      i18n: 'en',
      routes: [
        {
          url: 'test',
          links: ['en', 'fr', 'de'].map((lang) => ({ lang, url: `${lang}/test` })),
        },
      ],
    },
```

**Comment by NicholasAntidormi** [comment]
> Since the [v2.3.0](https://github.com/nuxt-community/sitemap-module/blob/dev/CHANGELOG.md#230-2020-05-11) the sitemap-module supports i18n routes from the nuxt-i18n module, but as before only for the static routes (see [features list](https://github.com/nuxt-community/sitemap-module#features))
> 
> But for now you can generate manually your dynamics routes with hreflang & alternate with the `links` attribute as follows:
> 
> ```js
> // nuxt.config.js
> 
>   i18n: {
>     locales: ['en', 'de', 'fr'],
>     defaultLocale: 'en',
>   },
>   sitemap: [
>     {
>       i18n: 'en',
>       routes: [
>         {
>           url: 'test',
>           links: ['en', 'fr', 'de'].map((lang) => ({ lang, url: `${lang}/test` })),
>         },
>       ],
>     },
> ```

Maybe it would be useful to have this in the doc (https://sitemap.nuxtjs.org/usage/sitemap-options#routes-declaration)
