### ISSUE TITLE
An option for trailing slash would improve SEO

### ISSUE THREAD

**Issue by egidioFrat** [nuxt-community/sitemap-module#34]
### What problem does this feature solve?

Missing trailing slash on URL of a directory force github pages to redirect HTTPS to HTTP.
https://github.com/isaacs/github/issues/289

### What does the proposed changes look like?

It could be an option to add trailing slash to static URL in sitemap.xml

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c32">#c32</a>)</em></sub></div>

**Comment by hareku** [comment]
Yes. I need to append trailing slash too.

**Comment by derevandal** [comment]
@egidioFrat @hareku 
I use `filter` feature:
```js
filter ({ routes }) {
  return routes.map(route => route.url = `${route.url}/`)
}
```

**Comment by NicoPennec** [comment]
@derevandal 
correct! since `sitemap-module` [v0.2](https://github.com/nuxt-community/sitemap-module/blob/dev/CHANGELOG.md#020-2019-01-02), use a custom filter is the simple way to fix the issue.

@egidioFrat @hareku 
if necessary, we can add a new option to the module in order to auto add a trailing slash on each route. Do you think is useful ? or add your custom filter is enough ?

**Comment by egidioFrat** [comment]
I guess this filter solution is enough. Thank you @derevandal and @NicoPennec

**Comment by bdrtsky** [comment]
This filter solution is not enough. I don't have dynamic urls. How do I add trailing slash then?

**Comment by bdrtsky** [comment]
@NicoPennec please add option to add trailing slash like you mention.
