### ISSUE TITLE
404 not found with firebase cloud functions

### ISSUE THREAD

**Issue by juloxrox** [nuxt-community/sitemap-module#43]
### Version

[0.2.0](https://github.com/sitemap-module/releases/tag/0.2.0)

### Reproduction link

[https://github.com/juloxrox/testsitemap](https://github.com/juloxrox/testsitemap)

### Steps to reproduce

Hi everyone,
When I do yarn dev or yarn build + yarn start I got sitemap.xml correctly generated when I visit /sitemap.xml.
But when it is served with firebase cloud functions, I get 404 not found. Don't know if it is firebase/nuxt/module related or am I missing something ?

I hosted an exemple here : https://github.com/juloxrox/testsitemap

Does someone has a solution for that please?
Thanks in advance

### What is expected ?

200 Response for /sitemap.xml

### What is actually happening?

404 not found

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c38">#c38</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
Hi @juloxrox

I did some tests with your example (https://github.com/juloxrox/testsitemap) and I confirm that the problem comes from your side.

If I try to add a new page `pages/test.vue` and deploy it on firebase, but I get the same 404 error.

Then I followed another tutorial on firebase (see https://github.com/williamchong007/nuxt-ssr-firebase) and added the sitemap module. After deploying to Firebase, it works fine (see https://bug-nuxt-sitemap-module.firebaseapp.com/sitemap.xml).

Maybe you could be inspired by this implementation of Functions: https://github.com/williamchong007/nuxt-ssr-firebase/blob/master/functions/index.js

**Comment by nwrightau** [comment]
>  After deploying to Firebase, it works fine (see https://bug-nuxt-sitemap-module.firebaseapp.com/sitemap.xml).

Are you able share your configuration for the version that you were able to get working? I'm experiencing the same issue.

**Comment by JoelCCodes** [comment]
I'm experiencing this as well. Any advice?

**Comment by sankhaKarunasekara** [comment]
I have the same issue?  Any advice.

**Comment by andrewmccrink** [comment]
After some research I found out that my issue was that sitemap.xml was not being added to my static folder during "nuxt build". If you manually add any .xml file into your static folder, you'll see that it will show up on production or while serving. So the end result for me was to write some scripts that got my sitemap.xml into the static folder. I found that running nuxt generate and then copying and pasting the sitemap file worked for me.

In my root package.json: `"build": "cd ./src && nuxt build && nuxt generate && npm run copysitemap"`
In my src package.json: `"copysitemap": "cp ./dist/sitemap.xml ./static"`
