### ISSUE TITLE
Support sitemap Etag Header

### ISSUE THREAD

**Issue by sonofmagic** [nuxt-community/sitemap-module#80]
### What problem does this feature solve?

Sitemap with Rtag can speed up search engine crawling. Baidu search engine  can respond to sitemap updates more quickly. refer:https://ziyuan.baidu.com/college/articleinfo?id=456

### What does the proposed changes look like?

options:{
  Etag:true
}

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sitemap-module/issues/c63">#c63</a>)</em></sub></div>

**Comment by NicoPennec** [comment]
I was not aware of this optimization by Etag Header optmization for the Baidu search engine 👍 

We should be able to take inspiration from this code from Nuxt: https://github.com/nuxt/nuxt.js/blob/76b1167d27b39a19ae2556334cd59e04ae19c1a8/packages/server/src/middleware/nuxt.js#L39-L49

**Comment by biosonic** [comment]
If possible, it would bi nice to add option to set custom HTTP response header. 
This approach would fix this issue, and my current issue which is that I'm not able to set Cache-Control headers for controlling nginx reverse proxy.
Should I open new issue?

**Comment by NicoPennec** [comment]
The ETag is now enabled by default, since release [v2.2.0](https://github.com/nuxt-community/sitemap-module/blob/dev/CHANGELOG.md#220-2020-04-05).
To override the default config, see [docs](https://github.com/nuxt-community/sitemap-module#etag-optional---object)

Thank @sonofmagic  for your proposal 🙏
It's a useful enhance for performance.
